package com.hk.community.model;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;
import lombok.ToString;

import java.io.Serializable;

/**
 * null
 * @TableName tb_category
 */
@Data
@ToString
@TableName(value = "tb_category")
public class Category implements Serializable {
    /**
     * 
     *
     * @mbg.generated 2021-04-22 20:42:02
     */
    @TableId(value = "id" , type = IdType.AUTO)
    private Integer id;

    /**
     * 
     *
     * @mbg.generated 2021-04-22 20:42:02
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_category
     *
     * @mbg.generated 2021-04-22 20:42:02
     */

}